function onCreate()
  makeLuaSprite('bg','weebSky',-200,0)
  setScrollFactor('bg',0.85,0.95)
  scaleObject('bg',7,7)
  makeLuaSprite('bg2','weebSchool',-250,0)
  setScrollFactor('bg2',0.85,0.95)
  scaleObject('bg2',7,7)
  makeLuaSprite('street','weebStreet',-200,100)
  makeLuaSprite('trees','weebTrees',-200, 0)
  scaleObject('trees',6,6)
  scaleObject('street',6.5,6)
  makeAnimatedLuaSprite('bg3','bgFreaks',-250,225)
  addAnimationByPrefix('bg3','idle','BG fangirls',24,true)
  objectPlayAnimation('bg3','idle',true)
  scaleObject('bg3',6,6)
  addLuaSprite('bg',false)
  addLuaSprite('bg2',false)
  addLuaSprite('street',false)
  addLuaSprite('trees',false)
  addLuaSprite('bg3',false)
  close(true);
  end